name: Update README

on:
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Monday
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository content
        uses: actions/checkout@v3

      - name: Run update script
        run: |
          python scripts/update_readme.py

      - name: Check if there are changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add README.md
            git commit -m "workflow: Updated README with latest member info"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Freundschaft-ist-Magie/.github.git
          else
            echo "No changes to commit."
          fi
